config/routes.rb
BudgetApp::Application.routes.draw do
  
  root :to => "Root#root"
  
  resource :session, :only => [:new, :create, :destroy]
  match '/guest_session', :controller => 'sessions', :action => 'create_guest_session'
  
  resources :users, :only => [:new, :create, :update, :show] do
    resources :budgets do
      resources :envelopes
    end
  end
  resources :transactions
  match '/main', :controller => 'users', :action => 'main'
  
  
  

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  attr_accessible :name, :user_id
  
  validates :name, :user_id, :presence => true
  
  validate :name_must_be_unique
  validate :user_id_must_be_valid
  
  belongs_to :user
  has_many :envelopes, :dependent => :destroy
  
  def envelopes_direct_descendants
    envelopes.where(:parent_env_id => nil)
  end
  
  private
  
  def name_must_be_unique 
    same_name_budgets = Budget.where(:name => self.name, :user_id => self.user_id)
    
    # so that it doesn't check the name of itself if it already exists
    if self.id
      same_name_budgets = same_name_budgets.where("id != ?", self.id)
    end
    
    return if same_name_budgets.empty?
    errors.add(:name, "already has a budget by that name")                                               
  end
  
  def user_id_must_be_valid
    return if User.exists?(self.user_id)
    errors.add(:user_id, "that user_id does not exist in the database")
  end
  
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  
  before_filter :require_current_user!
  
  def create
    params[:user_id] = current_user.id
    @budget = Budget.new(:name => params[:name], :user_id => params[:user_id])
    if @budget
      if @budget.save!
        render :json => @budget
      else
        flash[:errors] = @budget.errors.full_messages
      end
    else
      flash[:errors] = []
      flash[:errors] << "budget was nil and could not be saved"
    end
  end
  
  def new
    
  end
  
  def index
    @budgets = current_user.budgets
    render :index
  end
  
  def show
    @budget = Budget.find(params[:id])
    render :show
  end
  
  def edit
    
  end
  
  def update
    
  end
  
  def destroy
    @budget = Budget.find(params[:id])
    if @budget
      if @budget.destroy
        render :json => @budget
      else
        render :json => @budget.errors.full_messages
      end
    else
      render :json => "Budget was not found"
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/index.html.erb
<h1>Budgets Index</h1>
<% @budgets.each do |budget| %>
<%= link_to "#{budget.name}", user_budget_url(budget.user.id, budget.id) %>
<% end %>

app/views/budgets/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="row-fluid text-center">
        <div class="span6">
          Budget:
        </div>
        <div class="span6">
          <div class="budget-container_">
            budget
          </div>
        </div>
      </div>
      <br>
      <div class="row-fluid">
        <button class="btn btn-medium btn-block btn-primary">Add Envelope</button>
      </div>
      <br>
      <div class="row-fluid">
        <button class="btn btn-medium btn-block btn-primary">Remove Envelope</button>
      </div>
    </div>
    <div class="span7">
      <h1><%= @budget.name %></h1>

      <% def print_envelope(envelope) %>
        <% if envelope.child_envelopes.empty? %>
          <% return "<li>#{h envelope.name}</li>".html_safe %>
        <% else %>
          <% children = "<li>#{h envelope.name}</li><ul>" %>
            <% envelope.child_envelopes.each do |child| %>
              <% children += print_envelope(child) %>
            <% end %>
          <% children += "</ul>" %>

          <% return children.html_safe %>
        <% end %>
      <% end %>
      
      <% envelopes = @budget.envelopes_direct_descendants %>
      <ul>
        <% envelopes.each do |envelope| %>
          <%= print_envelope(envelope).html_safe %>
        <% end %>
      </ul>
    </div>
  </div>
</div>